adj1=input("Enter an adjective: ")
natn=input("Enter the nationality: ")
prsn=input("Enter the name of the person: ")
noun1=input("Enter a noun: ")
adj2=input("Enter an adjective: ")
noun2=input("Enter a noun: ")
adj3=input("Enter an adjective: ")
adj4=input("Enter an adjective: ")
pnoun=input("Enter a plural noun: ")
noun3=input("Enter a noun: ")
num1=input("Enter a number: ")
shapes=input("Enter the shape: ")
food1=input("Enter a name of a food: ")
food2=input("Enter a name of a food: ")
num2=input("Enter a number: ")
print("Pizza was invented by a " + adj1 +  natn + " chef named " + prsn + ".")
print("To make pizza, you need to take a lump of " + noun1 + " , and make a thin,round " + adj2  +  noun2 + ".")
print("Then you cover it with " + adj3 +  " sauce, " + adj4 + " cheese, and fresh chopped " + pnoun + ".")
print("Next you have to bake it in a very hot " + noun3 + ".")
print("When it is done,cut it into " + num1  +  shapes + ".")
print("Some kids like " + food1 + " pizza the best,but my favourite is the " + food2 + " pizza.")
print("If I could, I would eat pizza " + num2 + " times a day!")